export const ALL_TOOLS = [
  { id: "age-calculator", name: "Age Calculator", category: "health" },
  { id: "bmi-calculator", name: "BMI Calculator", category: "health" },
  { id: "percentage-calculator", name: "Percentage Calculator", category: "math" },
  { id: "loan-emi-calculator", name: "Loan EMI Calculator", category: "finance" },
  { id: "tip-calculator", name: "Tip Calculator", category: "finance" },
  { id: "discount-calculator", name: "Discount Calculator", category: "finance" },
  { id: "gpa-calculator", name: "GPA Calculator", category: "math" },
  { id: "fuel-cost-calculator", name: "Fuel Cost Calculator", category: "finance" },
  { id: "date-calculator", name: "Date Calculator", category: "productivity" },
  { id: "unit-price-calculator", name: "Unit Price Calculator", category: "finance" },
  { id: "compound-interest", name: "Compound Interest", category: "finance" },
  { id: "mortgage-calculator", name: "Mortgage Calculator", category: "finance" },
  { id: "proportion-calculator", name: "Proportion Calculator", category: "math" },
  { id: "ratio-calculator", name: "Ratio Calculator", category: "math" },
  { id: "average-calculator", name: "Average Calculator", category: "math" },
  { id: "equation-solver", name: "Equation Solver", category: "math" },
  { id: "gcf-lcm-calculator", name: "GCF & LCM Calculator", category: "math" },
  { id: "combinations-permutations", name: "Combinations & Permutations", category: "math" },
  { id: "decimal-to-fraction", name: "Decimal to Fraction", category: "math" },
  { id: "fraction-simplifier", name: "Fraction Calculator", category: "math" },
  { id: "prime-checker", name: "Prime Checker", category: "math" },
  { id: "graphing-calculator", name: "Graphing Calculator", category: "math" },
  { id: "matrix-calculator", name: "Matrix Calculator", category: "math" },
  { id: "periodic-table", name: "Periodic Table", category: "math" },
  { id: "shape-calculator", name: "2D Shape Calculator", category: "math" },
  { id: "body-calculator", name: "3D Body Calculator", category: "math" },
  { id: "sales-tax-calculator", name: "Sales Tax Calculator", category: "finance" },
  { id: "calorie-calculator", name: "Calorie Calculator", category: "health" },
  { id: "body-fat-calculator", name: "Body Fat Calculator", category: "health" },
  { id: "ohms-law-calculator", name: "Ohm's Law Calculator", category: "electronics" },
  { id: "unit-converter", name: "Unit Converter", category: "converters" },
  { id: "currency-converter", name: "Currency Converter", category: "converters" },
  { id: "temperature-converter", name: "Temperature Converter", category: "converters" },
  { id: "speed-converter", name: "Speed Converter", category: "converters" },
  { id: "weight-converter", name: "Weight Converter", category: "converters" },
  { id: "length-converter", name: "Length Converter", category: "converters" },
  { id: "time-converter", name: "Time Converter", category: "converters" },
  { id: "data-storage-converter", name: "Data Storage Converter", category: "converters" },
  { id: "color-converter", name: "Color Converter", category: "converters" },
  { id: "acceleration-converter", name: "Acceleration Converter", category: "converters" },
  { id: "angle-converter", name: "Angle Converter", category: "converters" },
  { id: "force-converter", name: "Force Converter", category: "converters" },
  { id: "torque-converter", name: "Torque Converter", category: "converters" },
  { id: "area-converter", name: "Area Converter", category: "converters" },
  { id: "volume-converter", name: "Volume Converter", category: "converters" },
  { id: "pressure-converter", name: "Pressure Converter", category: "converters" },
  { id: "energy-converter", name: "Energy Converter", category: "converters" },
  { id: "power-converter", name: "Power Converter", category: "converters" },
  { id: "volumetric-flow-converter", name: "Volumetric Flow Converter", category: "converters" },
  { id: "data-transfer-speed-converter", name: "Data Transfer Speed", category: "converters" },
  { id: "numeric-base-converter", name: "Numeric Base Converter", category: "converters" },
  { id: "roman-numerals-converter", name: "Roman Numerals Converter", category: "converters" },
  { id: "shoe-size-converter", name: "Shoe Size Converter", category: "converters" },
  { id: "ring-size-converter", name: "Ring Size Converter", category: "converters" },
  { id: "cooking-converter", name: "Cooking Converter", category: "converters" },
  { id: "mileage-converter", name: "Mileage Converter", category: "converters" },
  { id: "pdf-viewer", name: "PDF Viewer", category: "pdf" },
  { id: "pdf-merge", name: "PDF Merge", category: "pdf" },
  { id: "pdf-split", name: "PDF Split", category: "pdf" },
  { id: "pdf-compress", name: "PDF Compress", category: "pdf" },
  { id: "image-to-pdf", name: "Image to PDF", category: "pdf" },
  { id: "image-resizer", name: "Image Resizer", category: "image" },
  { id: "image-compressor", name: "Image Compressor", category: "image" },
  { id: "image-crop", name: "Image Crop", category: "image" },
  { id: "screenshot-stitcher", name: "Screenshot Stitcher", category: "image" },
  { id: "color-picker", name: "Color Picker", category: "image" },
  { id: "document-scanner", name: "Document Scanner", category: "image" },
  { id: "word-counter", name: "Word Counter", category: "text" },
  { id: "text-case-converter", name: "Text Case Converter", category: "text" },
  { id: "text-compare", name: "Text Compare", category: "text" },
  { id: "lorem-generator", name: "Lorem Generator", category: "generators" },
  { id: "text-repeater", name: "Text Repeater", category: "text" },
  { id: "character-counter", name: "Character Counter", category: "text" },
  { id: "markdown-preview", name: "Markdown Preview", category: "text" },
  { id: "text-to-speech", name: "Text to Speech", category: "text" },
  { id: "string-encoder", name: "String Encoder", category: "security" },
  { id: "text-chunker", name: "Text Chunker", category: "text" },
  { id: "diff-viewer", name: "Diff Viewer", category: "text" },
  { id: "json-formatter", name: "JSON Formatter", category: "formatters" },
  { id: "base64-encoder", name: "Base64 Encoder", category: "security" },
  { id: "uuid-generator", name: "UUID Generator", category: "developer" },
  { id: "regex-tester", name: "Regex Tester", category: "developer" },
  { id: "hash-generator", name: "Hash Generator", category: "security" },
  { id: "html-preview", name: "HTML Preview", category: "formatters" },
  { id: "jwt-decoder", name: "JWT Decoder", category: "security" },
  { id: "epoch-converter", name: "Epoch Converter", category: "developer" },
  { id: "color-palette-generator", name: "Color Palette Generator", category: "developer" },
  { id: "api-tester", name: "API Tester", category: "developer" },
  { id: "cron-expression", name: "Cron Expression Parser", category: "developer" },
  { id: "json-to-csv", name: "JSON to CSV", category: "developer" },
  { id: "chmod-calculator", name: "Chmod Calculator", category: "developer" },
  { id: "xml-formatter", name: "XML Formatter", category: "formatters" },
  { id: "sql-formatter", name: "SQL Formatter", category: "formatters" },
  { id: "number-base-converter", name: "Number Base Converter", category: "developer" },
  { id: "yaml-to-json", name: "YAML to JSON", category: "developer" },
  { id: "prompt-template-builder", name: "Prompt Template Builder", category: "ai" },
  { id: "token-counter", name: "Token Counter", category: "ai" },
  { id: "markdown-to-json", name: "Markdown to JSON", category: "developer" },
  { id: "api-payload-explorer", name: "API Payload Explorer", category: "developer" },
  { id: "ai-safety-checker", name: "AI Safety Checker", category: "ai" },
  { id: "uuid-hash-audit", name: "UUID + Hash Audit", category: "developer" },
  { id: "totp-tester", name: "TOTP Tester", category: "security" },
  { id: "aes-encrypt-decrypt", name: "AES Encrypt / Decrypt", category: "security" },
  { id: "hmac-generator", name: "HMAC Generator", category: "security" },
  { id: "qr-scanner", name: "QR Scanner", category: "qr" },
  { id: "qr-generator", name: "QR Generator", category: "qr" },
  { id: "barcode-scanner", name: "Barcode Scanner", category: "qr" },
  { id: "nfc-reader", name: "NFC Reader", category: "nfc" },
  { id: "nfc-writer", name: "NFC Writer", category: "nfc" },
  { id: "nfc-info", name: "NFC Info", category: "nfc" },
  { id: "wifi-nfc-writer", name: "WiFi NFC Writer", category: "nfc" },
  { id: "device-info", name: "Device Info", category: "device" },
  { id: "battery-monitor", name: "Battery Monitor", category: "device" },
  { id: "storage-analyzer", name: "Storage Analyzer", category: "device" },
  { id: "audio-format-guide", name: "Audio Format Guide", category: "device" },
  { id: "bpm-tapper", name: "BPM Tapper", category: "device" },
  { id: "frequency-analyzer", name: "Frequency Analyzer", category: "device" },
  { id: "tone-generator", name: "Tone Generator", category: "device" },
  { id: "compass", name: "Compass", category: "device" },
  { id: "light-meter", name: "Light Meter", category: "device" },
  { id: "sound-meter", name: "Sound Meter", category: "device" },
  { id: "accelerometer-viewer", name: "Accelerometer Viewer", category: "device" },
  { id: "gyroscope-viewer", name: "Gyroscope Viewer", category: "device" },
  { id: "speed-test", name: "Speed Test", category: "network" },
  { id: "wifi-strength", name: "WiFi Strength", category: "network" },
  { id: "ping-tool", name: "Ping Tool", category: "network" },
  { id: "ip-lookup", name: "IP Lookup", category: "network" },
  { id: "dns-lookup", name: "DNS Lookup", category: "network" },
  { id: "http-status-codes", name: "HTTP Status Codes", category: "network" },
  { id: "password-generator", name: "Password Generator", category: "generators" },
  { id: "random-number-generator", name: "Random Number Generator", category: "generators" },
  { id: "dice-roller", name: "Dice Roller", category: "generators" },
  { id: "coin-flipper", name: "Coin Flipper", category: "generators" },
  { id: "color-randomizer", name: "Color Randomizer", category: "generators" },
  { id: "name-generator", name: "Name Generator", category: "generators" },
  { id: "countdown-timer", name: "Countdown Timer", category: "productivity" },
  { id: "pomodoro-timer", name: "Pomodoro Timer", category: "productivity" },
  { id: "habit-tracker", name: "Habit Tracker", category: "productivity" },
  { id: "notes-tool", name: "Notes Tool", category: "productivity" },
  { id: "stopwatch", name: "Stopwatch", category: "productivity" },
  { id: "expense-tracker", name: "Expense Tracker", category: "productivity" },
  { id: "world-clock", name: "World Clock", category: "productivity" },
  { id: "daily-planner", name: "Daily Planner", category: "productivity" },
  { id: "resistor-color-code", name: "Resistor Color Code", category: "electronics" },
  { id: "smd-resistor-code", name: "SMD Resistor Code", category: "electronics" },
  { id: "ohms-law", name: "Ohm's Law Calculator", category: "electronics" },
  { id: "voltage-divider", name: "Voltage Divider", category: "electronics" },
  { id: "led-resistor", name: "LED Resistor Calculator", category: "electronics" },
  { id: "resistor-series-parallel", name: "Resistor Series / Parallel", category: "electronics" },
  { id: "capacitor-series-parallel", name: "Capacitor Series / Parallel", category: "electronics" },
  { id: "power-calculator-ee", name: "Power Calculator", category: "electronics" },
  { id: "battery-life", name: "Battery Life Calculator", category: "electronics" },
  { id: "capacitor-charge", name: "RC Time Constant", category: "electronics" },
  { id: "resistor-ratio", name: "Resistor Ratio Finder", category: "electronics" },
  { id: "ne555-calculator", name: "NE555 Calculator", category: "electronics" },
  { id: "inductor-color-code", name: "Inductor Color Code", category: "electronics" },
  { id: "reactance-resonance", name: "Reactance & Resonance", category: "electronics" },
  { id: "filter-calculator", name: "Filter Calculator", category: "electronics" },
  { id: "op-amp-calculator", name: "Op-Amp Calculator", category: "electronics" },
  { id: "voltage-regulator", name: "Voltage Regulator", category: "electronics" },
  { id: "voltage-drop", name: "Voltage Drop Calculator", category: "electronics" },
  { id: "pcb-trace-width", name: "PCB Trace Width", category: "electronics" },
  { id: "power-dissipation", name: "Power Dissipation", category: "electronics" },
  { id: "frequency-converter-ee", name: "Frequency Converter", category: "electronics" },
  { id: "adc-calculator", name: "ADC Calculator", category: "electronics" },
  { id: "heart-rate-calculator", name: "Heart Rate Calculator", category: "health" },
  { id: "blood-pressure-logger", name: "Blood Pressure Logger", category: "health" },
  { id: "water-intake-calculator", name: "Water Intake Calculator", category: "health" },
  { id: "sleep-calculator", name: "Sleep Calculator", category: "health" },
  { id: "bac-calculator", name: "BAC Calculator", category: "health" },
  { id: "waist-hip-ratio", name: "Waist-to-Hip Ratio", category: "health" },
  { id: "pace-calculator", name: "Pace Calculator", category: "health" },
  { id: "one-rep-max", name: "One-Rep Max Calculator", category: "health" },
  { id: "pregnancy-due-date", name: "Pregnancy Due Date", category: "health" },
  { id: "ovulation-calculator", name: "Ovulation Calculator", category: "health" },
  { id: "ideal-weight-calculator", name: "Ideal Weight Calculator", category: "health" },
  { id: "macro-calculator", name: "Macro Calculator", category: "health" },
] as const;

export type ToolInfo = (typeof ALL_TOOLS)[number];
